library(tidyverse)
library(lubridate)
library(dplyr)
daily <- read.csv("/kaggle/input/fitbit/Fitabase Data 4.12.16-5.12.16/dailyActivity_merged.csv")
sleep <- read.csv("/kaggle/input/fitbit/Fitabase Data 4.12.16-5.12.16/sleepDay_merged.csv")
weight <- read.csv("/kaggle/input/fitbit/Fitabase Data 4.12.16-5.12.16/weightLogInfo_merged.csv")
intensity <- read.csv("/kaggle/input/fitbit/Fitabase Data 4.12.16-5.12.16/hourlyIntensities_merged.csv")
head(daily)
head(sleep)
head(weight)
head(intensity)
n_distinct(daily$Id)
n_distinct(sleep$Id)
n_distinct(intensity$Id)
n_distinct(weight$Id)
sleep <- sleep %>% mutate(ActivityDate = as.Date(SleepDay, format = "%m/%d/%y"))
sleep <- sleep %>% select(-"SleepDay")
daily <- daily %>% mutate(ActivityDate = as.Date(ActivityDate, format = "%m/%d/%y"))
weight <- weight %>% mutate(ActivityDate = as.Date(Date))
weight <- weight %>% select(-"Date")
full <- inner_join(daily, sleep, by = c("Id", "ActivityDate"))
summary(daily)
summary(sleep)
summary(full)
ggplot(data = daily) + geom_point(mapping = aes(x= TotalSteps, y = Calories)) + geom_smooth(mapping = aes(x= TotalSteps, y = Calories)) + labs(title = "Calories vs Total Steps")
ggplot(data = daily) + geom_point(mapping = aes(x= VeryActiveMinutes, y = Calories, alpha=Calories), color="red") + geom_point(mapping = aes(x=LightlyActiveMinutes, y = Calories, alpha=Calories), color = "darkgreen") + labs(title = "Calories vs Active Minutes", x = "Active Minutes")
ggplot(data = sleep) + geom_point(mapping = aes(x=TotalTimeInBed, y = TotalMinutesAsleep)) + labs(title = "Total time in bed vs in asleep")
